baseURL = "https://blog.librecourse.uy"
languageCode = "es-UY"
title = "LibreCourseUY"
theme = "PaperMod"

[params]
  description = "Blog de LibreCourse"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Codenights"
    url = "/codenights/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
