baseURL = "https://blog.librecourse.uy"
title = "🇺🇾 LibreCourseUY"
theme = "PaperMod"

[languages.en]
  locale = "en-US"
  weight = 1

[params]
  description = "LibreCourseUY Dev Log"

[params.homeInfoParams]
  Title = "LibreCourseUY Latest Updates"
  Content = ""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Codenights"
    url = "/codenights/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3